from fpdf import FPDF

def generate_ticket_pdf(chain, train_no, date, start_stn, end_stn):
    """
    Generates a PDF 'Hacker Ticket' for the journey.
    """
    class PDF(FPDF):
        def header(self):
            self.set_fill_color(46, 125, 50) # Green
            self.rect(0, 0, 210, 40, 'F')
            self.set_font('Arial', 'B', 24)
            self.set_text_color(255, 255, 255)
            self.cell(0, 20, 'TRAIN SURFER', 0, 1, 'C')
            self.set_font('Arial', '', 12)
            self.cell(0, 10, 'HACKER ITINERARY', 0, 1, 'C')
            self.ln(20)

        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.set_text_color(128)
            self.cell(0, 10, 'Generated by Train Surfer V2 - Not an official ticket', 0, 0, 'C')

    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Meta Info
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(0)
    pdf.cell(95, 10, f"TRAIN: {train_no}", 0, 0)
    pdf.cell(95, 10, f"DATE: {date}", 0, 1)
    pdf.cell(0, 10, f"ROUTE: {start_stn} -> {end_stn}", 0, 1)
    pdf.ln(10)

    # Legs
    for i, leg in enumerate(chain):
        pdf.set_fill_color(240, 240, 240)
        pdf.rect(10, pdf.get_y(), 190, 35, 'F')
        
        pdf.set_font("Arial", "B", 14)
        pdf.set_text_color(46, 125, 50)
        pdf.cell(100, 10, f"LEG {i+1}", 0, 0)
        
        pdf.set_font("Arial", "B", 12)
        pdf.set_text_color(0)
        pdf.cell(90, 10, f"{leg['Coach']} - {leg['Berth']} ({leg['Type']})", 0, 1, 'R')
        
        pdf.set_font("Arial", "", 12)
        pdf.cell(60, 10, leg['From'], 0, 0, 'C')
        pdf.cell(70, 10, f"--- {leg['Distance']} km ---", 0, 0, 'C')
        pdf.cell(60, 10, leg['To'], 0, 1, 'C')
        
        pdf.ln(5)
        
        if i < len(chain) - 1:
            pdf.set_font("Arial", "B", 10)
            pdf.set_text_color(180, 0, 0)
            pdf.cell(0, 10, "v SWAP SEATS HERE v", 0, 1, 'C')
            pdf.ln(5)
        else:
            pdf.ln(10)

    return pdf.output(dest='S').encode('latin-1')

def render_route_map(station_list, start_code, end_code):
    """
    Renders a visual map of the full route segment.
    """
    # Filter stations between start and end
    try:
        start_idx = next(i for i, s in enumerate(station_list) if s['code'] == start_code)
        end_idx = next(i for i, s in enumerate(station_list) if s['code'] == end_code)
        segment = station_list[start_idx : end_idx+1]
    except StopIteration:
        return ""

    html = f"""
<div style="font-family: 'Segoe UI', sans-serif; background: white; padding: 15px; border-radius: 8px; border: 1px solid #e0e0e0; margin-bottom: 20px;">
    <div style="font-size: 12px; color: #666; margin-bottom: 15px;">Showing {len(segment)} stations from <b>{start_code}</b> to <b>{end_code}</b></div>
    <div style="display: flex; overflow-x: auto; padding-bottom: 15px; align-items: flex-start;">
"""
    
    for i, stn in enumerate(segment):
        is_start = i == 0
        is_end = i == len(segment) - 1
        is_active = is_start or is_end
        
        dot_color = "#2E7D32" if is_active else "#bdbdbd"
        dot_size = "14px" if is_active else "10px"
        font_weight = "bold" if is_active else "normal"
        text_color = "#000" if is_active else "#555"
        
        # Line colors
        line_left = "transparent" if is_start else "#e0e0e0"
        line_right = "transparent" if is_end else "#e0e0e0"
        
        # Format name
        name_display = stn['name'].title() if stn['name'] else ""
        if name_display.upper() == stn['code']: name_display = "" # Hide if same
        
        html += f"""
<div style="display: flex; flex-direction: column; align-items: center; min-width: 100px; position: relative;">
    <div style="display: flex; align-items: center; width: 100%; height: 20px; margin-bottom: 8px;">
        <div style="height: 2px; background: {line_left}; width: 50%;"></div>
        <div style="width: {dot_size}; height: {dot_size}; background: {dot_color}; border-radius: 50%; flex-shrink: 0; z-index: 1;"></div>
        <div style="height: 2px; background: {line_right}; width: 50%;"></div>
    </div>
    <span style="font-weight: {font_weight}; color: {text_color}; font-size: 13px;">{stn['code']}</span>
    <span style="font-size: 11px; color: #666; text-align: center; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 90px;" title="{name_display}">{name_display}</span>
    <span style="font-size: 10px; color: #999; margin-top: 2px;">{stn['dist']} km</span>
</div>
"""
            
    html += """
    </div>
</div>
"""
    return html

def render_visual_timeline(chain, station_list):
    """
    Returns HTML for a horizontal visual timeline of the journey.
    Includes intermediate stations.
    """
    total_legs = len(chain)
    
    # Helper to find station index
    stn_indices = {s['code']: i for i, s in enumerate(station_list)}
    
    # Start of HTML string (Single line)
    html = '<div style="display: flex; align-items: center; overflow-x: auto; padding: 20px 0; font-family: sans-serif;">'
    
    for i, leg in enumerate(chain):
        # Color code based on berth type
        color = "#4CAF50" # Green (Default/LB)
        if leg['Type'] in ['MB', 'UB', 'SM', 'SU', 'M', 'U']:
            color = "#FFC107" # Yellow (Warning)
            
        # Calculate intermediates
        try:
            s_idx = stn_indices.get(leg['From'])
            e_idx = stn_indices.get(leg['To'])
            intermediates = []
            if s_idx is not None and e_idx is not None and e_idx > s_idx + 1:
                # Get stations between start and end
                intermediates = [s['code'] for s in station_list[s_idx+1 : e_idx]]
        except Exception:
            intermediates = []
            
        int_text = ""
        if intermediates:
            count = len(intermediates)
            names = ", ".join(intermediates)
            # Use a simple, robust title tooltip. 
            # Streamlit strips some interactive JS/CSS, so standard title is safest.
            int_text = f'<div title="Stops: {names}" style="font-size: 10px; color: #eee; margin-top: 2px; cursor: help; border-top: 1px dashed rgba(255,255,255,0.5); padding-top: 2px;">{count} stops ℹ️</div>'
        
        # Build leg HTML (Minified)
        leg_html = f"""<div style="flex: 1; min-width: 140px; text-align: center; position: relative;"><div style="background: {color}; color: white; padding: 10px; border-radius: 8px; margin: 0 5px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);"><div style="font-weight: bold; font-size: 16px;">{leg['Coach']} - {leg['Berth']}</div><div style="font-size: 12px; opacity: 0.9;">{leg['Type']}</div><div style="font-size: 11px; margin-top: 4px;">{leg['From']} &#8594; {leg['To']}</div>{int_text}</div>{f'<div style="position: absolute; right: -12px; top: 50%; transform: translateY(-50%); z-index: 1; background: white; border: 1px solid #ccc; border-radius: 50%; width: 24px; height: 24px; display: flex; align-items: center; justify-content: center; font-size: 12px;">&#127939;</div>' if i < total_legs-1 else ''}</div>"""
        html += leg_html
    
    html += '</div>'
    return html
